module VtexResponses

  def self.elegible_orders_list(quantity: 1)
    list = []
    quantity.times do |i|
      hash = {:orderId=>"883183166691-0#{i}",
              :creationDate=>"2018-12-13T13:53:00.0000000+00:00",
              :clientName=>"ananda namba",
              :items=>nil,
              :totalValue=>15000.0,
              :paymentNames=>"Mastercard",
              :status=>"ready-for-handling",
              :statusDescription=>"Pronto para o manuseio",
              :marketPlaceOrderId=>nil,
              :sequence=>"505027",
              :salesChannel=>"1",
              :affiliateId=>"",
              :origin=>"Marketplace",
              :workflowInErrorState=>false,
              :workflowInRetry=>false,
              :lastMessageUnread=>" SUA COMPRA FOI APROVADA Olá ananda, Recebemos a confirmação de pagamento do pedido: 883183166691-01. Acompanhe o andamento de seu pedido em",
              :ShippingEstimatedDate=>"2018-12-18T13:53:31.0000000+00:00",
              :orderIsComplete=>true,
              :listId=>nil,
              :listType=>nil,
              :authorizedDate=>"2018-12-13T13:53:44.0000000+00:00",
              :callCenterOperatorName=>nil,
              :totalItems=>1,
              :currencyCode=>"BRL"}
      list << hash
    end
    list
  end

  def self.elegible_order_data(quantity: 1, item_price: 15000, category_id: '106', non_elegible_quantity: 5)
    {:orderId=>"883183166691-01",
     :sequence=>"505027",
     :marketplaceOrderId=>"",
     :marketplaceServicesEndpoint=>"http://portal.vtexcommerce.com.br/api/oms?an=klasme",
     :sellerOrderId=>"00-883183166691-01",
     :origin=>"Marketplace",
     :affiliateId=>"",
     :salesChannel=>"1",
     :merchantName=>nil,
     :status=>"ready-for-handling",
     :statusDescription=>"Pronto para o manuseio",
     :value=>15000,
     :creationDate=>"2018-12-13T13:53:00.2075514+00:00",
     :lastChange=>"2018-12-13T14:23:27.4354719+00:00",
     :orderGroup=>"883183166691",
     :totals=>[
       {:id=>"Items",
        :name=>"Total dos Itens",
        :value=>15000
     },
     {:id=>"Discounts",
      :name=>"Total dos Descontos",
      :value=>0
     },
     {:id=>"Shipping",
      :name=>"Total do Frete",
      :value=>0
     },
     {:id=>"Tax",
      :name=>"Total da Taxa",
      :value=>0
     }
     ],
     :items=> generate_items(item_price, quantity, category_id, non_elegible_quantity),
     :marketplaceItems=>[],
     :clientProfileData=>
     {:id=>"clientProfileData",
      :email=>"6f4c0ac5ce414bb29953727c781f6269@ct.vtex.com.br",
      :firstName=>"ananda",
      :lastName=>"namba",
      :documentType=>"cpf",
      :document=>"22928872825",
      :phone=>"+5511981640273",
      :corporateName=>nil,
      :tradeName=>nil,
      :corporateDocument=>nil,
      :stateInscription=>nil,
      :corporatePhone=>nil,
      :isCorporate=>false,
      :userProfileId=>"1a044cf9-52a9-4f94-be44-6efcedd1062d",
      :customerClass=>nil},
      :giftRegistryData=>nil,
      :marketingData=>
      {:id=>"marketingData",
        :utmSource=>nil,
        :utmPartner=>nil,
        :utmMedium=>nil,
        :utmCampaign=>nil,
        :coupon=>nil,
        :utmiCampaign=>nil,
        :utmipage=>nil,
        :utmiPart=>nil,
        :marketingTags=>[]},
        :ratesAndBenefitsData=>
        {:id=>"ratesAndBenefitsData",
          :rateAndBenefitsIdentifiers=>[
            {:description=>"Desconto de frete grátis para compras com valor acima de R$ 129,00",
              :featured=>false,
              :id=>"494b509e-f2f4-40d8-955e-ecba2d471326",
              :name=>"Frete grátis",
              :matchedParameters=>{},
              :additionalInfo=>nil}
            ]},
            :shippingData=>
            {:id=>"shippingData",
            :address=>
            {:addressType=>"residential",
            :receiverName=>"ananda namba",
            :addressId=>"3a48980629e9408f917e3040b4f01400",
            :postalCode=>"03152-060",
            :city=>"São Paulo",
            :state=>"SP",
            :country=>"BRA",
            :street=>"Rua Poá",
            :number=>"85",
            :neighborhood=>"Quinta da Paineira",
            :complement=>nil,
            :reference=>nil,
            :geoCoordinates=>[]},
            :logisticsInfo=>[
            {:itemIndex=>0,
            :selectedSla=>"SEDEX",
            :lockTTL=>"12d",
            :price=>0,
            :listPrice=>1009,
            :sellingPrice=>0,
            :deliveryWindow=>nil,
            :deliveryCompany=>"SEDEX S/CONTRATO",
            :shippingEstimate=>"3bd",
            :shippingEstimateDate=>"2018-12-18T13:53:31.5705531+00:00",
            :slas=>[
            {:id=>"SEDEX",
            :name=>"SEDEX",
            :shippingEstimate=>"3bd",
            :deliveryWindow=>nil,
            :price=>0,
            :deliveryChannel=>"delivery",
            :pickupStoreInfo=> {:additionalInfo=>nil,
            :address=>nil,
            :dockId=>nil,
            :friendlyName=>nil,
            :isPickupStore=>false},
            :polygonName=>nil}],
            :shipsTo=>["BRA"],
            :deliveryIds=>[
            {:courierId=>"172f046",
            :courierName=>"SEDEX S/CONTRATO",
            :dockId=>"1",
            :quantity=>1,
            :warehouseId=>"1_1"}],
            :deliveryChannel=>"delivery",
            :pickupStoreInfo=>
            {:additionalInfo=>nil,
            :address=>nil,
            :dockId=>nil,
            :friendlyName=>nil,
            :isPickupStore=>false},
            :addressId=>"3a48980629e9408f917e3040b4f01400",
            :polygonName=>nil}],
            :trackingHints=>nil,
            :selectedAddresses=>[
            {:addressId=>"3a48980629e9408f917e3040b4f01400",
            :addressType=>"residential",
            :receiverName=>"ananda namba",
            :street=>"Rua Poá",
            :number=>"85",
            :complement=>nil,
            :neighborhood=>"Quinta da Paineira",
            :postalCode=>"03152-060",
            :city=>"São Paulo",
            :state=>"SP",
            :country=>"BRA",
            :reference=>nil,
            :geoCoordinates=>[]}]},
            :paymentData=>
            {:transactions=>[
            {:isActive=>true,
            :transactionId=>"E65AD9F0475044BC9FEDA52056EB9672",
            :merchantName=>"KLASME",
            :payments=>[
            {:id=>"51BEE3E86FB34CB19CCA59EE78C01B28",
            :paymentSystem=>"4",
            :paymentSystemName=>"Mastercard",
            :value=>15000,
            :installments=>1,
            :referenceValue=>15000,
            :cardHolder=>nil,
            :cardNumber=>nil,
            :firstDigits=>"550209",
            :lastDigits=>"3945",
            :cvv2=>nil,
            :expireMonth=>nil,
            :expireYear=>nil,
            :url=>nil,
            :giftCardId=>nil,
            :giftCardName=>nil,
            :giftCardCaption=>nil,
            :redemptionCode=>nil,
            :group=>"creditCard",
            :tid=>"66629846",
            :dueDate=>nil,
            :connectorResponses=>
            {:Tid=>"66629846",
            :ReturnCode=>"undefined",
            :Message=>nil,
            :authId=>"66629846"}}]}]},
            :packageAttachment=>
            {:packages=>[]},
            :sellers=>[
            {:id=>"1",
            :name=>"KLASME",
            :logo=>""}],
            :callCenterOperatorData=>nil,
            :followUpEmail=>"157aef477efa40a6890cea8ee88d87c4@ct.vtex.com.br",
            :lastMessage=>nil,
            :hostname=>"klasme",
            :invoiceData=>nil,
            :changesAttachment=>nil,
            :openTextField=>nil,
            :roundingError=>0,
            :orderFormId=>"317f130e9cf44267aac951c4f979de04",
            :commercialConditionData=>nil,
            :isCompleted=>true,
            :customData=>nil,
            :storePreferencesData=>
            {:countryCode=>"BRA",
            :currencyCode=>"BRL",
            :currencyFormatInfo=>
            {:CurrencyDecimalDigits=>2,
            :CurrencyDecimalSeparator=>",",
            :CurrencyGroupSeparator=>".",
            :CurrencyGroupSize=>3,
            :StartsWithCurrencySymbol=>true},
            :currencyLocale=>1046,
            :currencySymbol=>"R$",
            :timeZone=>"E. South America Standard Time"},
            :allowCancellation=>true,
            :allowEdition=>false,
            :isCheckedIn=>false,
            :marketplace=>
            {:baseURL=>"http://portal.vtexcommerce.com.br/api/oms?an=klasme",
            :isCertified=>nil,
            :name=>"klasme"},
            :authorizedDate=>"2018-12-13T13:53:14.0000000+00:00",
            :invoicedDate=>nil}
   end

  def self.generate_items(item_price, quantity, category_id, non_elegible_quantity)
    items = []
    quantity.times do
      item_hash = {
        :uniqueId=>"5691328415B649FDA6DF203641C977A9",
        :id=>"205",
        :productId=>"5304",
        :ean=>nil,
        :lockId=>"00-883183166691-01",
        :itemAttachment=>
        {:content=>{},
        :name=>nil},
        :attachments=>[],
        :quantity=>1,
        :seller=>"1",
        :name=>"Kit Natal Acessórios",
        :refId=>"kit01",
        :price=>item_price,
        :listPrice=>19920,
        :manualPrice=>nil,
        :priceTags=>[
        {:name=>"discount@shipping-494b509e-f2f4-40d8-955e-ecba2d471326#8e029643-8df3-4df2-bca5-313f82b86dc6",
        :value=>-1009,
        :isPercentual=>false,
        :identifier=>"494b509e-f2f4-40d8-955e-ecba2d471326",
        :rawValue=>-10.09}],
        :imageUrl=>"http://klasme.vteximg.com.br/arquivos/ids/155988-88-88/KIT-ACESSORIOS.jpg?v=636802130479200000",
        :detailUrl=>"/kit-natal-acessorios/p",
        :components=>[],
        :bundleItems=>[],
        :params=>[],
        :offerings=>[],
        :sellerSku=>"205",
        :priceValidUntil=>nil,
        :commission=>0,
        :tax=>0,
        :preSaleDate=>nil,
        :additionalInfo=>
        {:brandName=>"Klasme",
        :brandId=>"593234054",
        :categoriesIds=>"/#{category_id}/",
        :productClusterId=>"138",
        :commercialConditionId=>"1",
        :dimension=>
        {:cubicweight=>1.0,
        :height=>10.0,
        :length=>18.0,
        :weight=>34.7,
        :width=>27.0},
        :offeringInfo=>nil,
        :offeringType=>nil,
        :offeringTypeId=>nil},
        :measurementUnit=>"un",
        :unitMultiplier=>1.0,
        :sellingPrice=>item_price,
        :isGift=>false,
        :shippingPrice=>nil,
        :rewardValue=>0,
        :freightCommission=>0,
        :priceDefinitions=>nil,
        :taxCode=>""
      }
      items << item_hash
    end

    non_elegible_quantity.times do
      item_hash = {
        :uniqueId=>"5691328415B649FDA6DF203641C977A9",
        :id=>"205",
        :productId=>"5304",
        :ean=>nil,
        :lockId=>"00-883183166691-01",
        :itemAttachment=>
        {:content=>{},
        :name=>nil},
        :attachments=>[],
        :quantity=>1,
        :seller=>"1",
        :name=>"Kit Natal Acessórios",
        :refId=>"kit01",
        :price=> 9901,
        :listPrice=>19920,
        :manualPrice=>nil,
        :priceTags=>[
        {:name=>"discount@shipping-494b509e-f2f4-40d8-955e-ecba2d471326#8e029643-8df3-4df2-bca5-313f82b86dc6",
        :value=>-1009,
        :isPercentual=>false,
        :identifier=>"494b509e-f2f4-40d8-955e-ecba2d471326",
        :rawValue=>-10.09}],
        :imageUrl=>"http://klasme.vteximg.com.br/arquivos/ids/155988-88-88/KIT-ACESSORIOS.jpg?v=636802130479200000",
        :detailUrl=>"/kit-natal-acessorios/p",
        :components=>[],
        :bundleItems=>[],
        :params=>[],
        :offerings=>[],
        :sellerSku=>"205",
        :priceValidUntil=>nil,
        :commission=>0,
        :tax=>0,
        :preSaleDate=>nil,
        :additionalInfo=>
        {:brandName=>"Klasme",
        :brandId=>"593234054",
        :categoriesIds=>"/999/",
        :productClusterId=>"138",
        :commercialConditionId=>"1",
        :dimension=>
        {:cubicweight=>1.0,
        :height=>10.0,
        :length=>18.0,
        :weight=>34.7,
        :width=>27.0},
        :offeringInfo=>nil,
        :offeringType=>nil,
        :offeringTypeId=>nil},
        :measurementUnit=>"un",
        :unitMultiplier=>1.0,
        :sellingPrice=>9901,
        :isGift=>false,
        :shippingPrice=>nil,
        :rewardValue=>0,
        :freightCommission=>0,
        :priceDefinitions=>nil,
        :taxCode=>""
      }
      items << item_hash
    end

    return items
  end
end
